<?php

$this->headTitle('Sign in');

//$this->mainMenu()->setActiveItemId('login');

//$form->get('login')->setAttributes([
//    'class'=>'form-control',
//    'placeholder'=>'Login',
//    'required' => true,
//    'autofocus' => true
//])
//    ->setLabelAttributes([
//        'class' => 'sr-only'
//    ]);

?>
<div class="jumbotron">
    <h1 class="display-4">Страница аутентификации<br><a href="<?= $this->url('about', ['action' => 'about']); ?>" >
            EDS Manager</h1>

    <hr class="my-4">

        <a class="btn btn-primary btn-lg " href="https://github.com/EDSManager/EDSManager-Laminas" target="_blank">
            EDS Manager на GitHub &raquo;
        </a>


</div>

