<?php
$this->headTitle('Users');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Manage Users'=>$this->url('users'),
            ]);
?>

<h1>Manage Users</h1>

<p>
<a class="btn btn-info" href="
    <?= $this->url('users', ['action'=>'add']); ?>">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New User
</a>
</p>

<table class="table table-striped">

   <tr>
        <th>ID</th>
        <th>Login</th>
        <th>Status</th>
        <th>Person</th>
        <th>Date Last Login</th>

    </tr>
    
    <?php foreach ($users as $user): ?>
    
    <tr>
        <td><?= $this->escapeHtml($user->getId()); ?></td>

        <td>
            <a href="<?= $this->url('users', ['action'=>'view', 'id'=>$user->getId()]); ?>">
                <?= $this->escapeHtml($user->getLogin()); ?>
            </a> 
        </td>
        <td><?= $this->escapeHtml($user->getStatusAsString()); ?></td>
        <td><?= $this->escapeHtml($user->getPersonFullName()); ?></td>
        <td><?= $this->escapeHtml($user->getDateLastLogin()); ?></td>
    </tr>
        
    <?php endforeach; ?>   
    
</table>

<?= $this->paginationControl($users,
                    'Sliding',
                    'user/partial/paginator', 
                    array('route' => 'users')); ?>


