<?php
$this->headTitle('View User');

$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Manage Users'=>$this->url('users'),
            'View User'=>$this->url('users', ['action'=>'view', 'id'=>$user->getId()])
            ]);
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<h1>View User</h1>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($user->getId()) ?></th>
            </tr>
            <tr>
                <th>Login:</th>
                <td><?= $this->escapeHtml($user->getLogin()) ?></th>
            </tr>

            <tr>
                <th>Date Created:</th>
                <td><?= $this->escapeHtml($user->getDateCreated()) ?></th>
            </tr>
            <tr>
                <th>Status:</th>
                <td><?= $this->escapeHtml($user->getStatusAsString()) ?></th>
            </tr>
            <tr>
                <th>Date Last Login:</th>
                <td><?= $this->escapeHtml($user->getDateLastLogin()) ?></th>
            </tr>
            <tr>
                <th>Person ID:</th>
                <td><?= $this->escapeHtml($user->getPersonId()) ?></th>
            </tr>

            <tr>
                <th>Person Full Name:</th>
                <td><?= $this->escapeHtml($user->getPersonFullName()) ?></th>
            </tr>

            <tr>
                <th>Person E-Mail:</th>
                <td><?= $this->escapeHtml($user->getPersonEmail()) ?></th>
            </tr>



        </table>

        <a class="btn btn-info" href="<?= $this->url('users',
            ['action'=>'edit', 'id'=>$user->getId()]); ?>">
            <span class="glyphicon glyphicon-pencil" ></span> Edit
        </a>

        <a class="btn btn-info" href="<?= $this->url('users',
            ['action'=>'change-password', 'id'=>$user->getId()]); ?>">
            <span class="glyphicon glyphicon-asterisk"></span> Change Password
        </a>

    </div>
</div>