<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('EDS Manager')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink([
                                'rel' => 'shortcut icon',
                                'type' => 'image/vnd.microsoft.icon',
                                'href' => $this->basePath() . '/img/favicon.ico'
                            ])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.5.1.min.js'))
        ?>

    </head>

    <body>
    <nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="<?= $this->url('home') ?>">
                    <img src="<?= $this->basePath('img/edsmanager-logo.svg') ?>" alt="EDSManager">
                </a>
            </div>
        </div>


    </nav>

        <div class="row">
            <div class="col-md-2">
                <!-- Navigation bar -->
                <?php
                // Check if the activeMenuItemId passed to layout view model
                // and if so, use it for setting active navbar item.
                if (isset($activeMenuItemId)) {
                    $this->mainMenu()->setActiveItemId($activeMenuItemId);
                }

                // Render the navbar
                echo $this->mainMenu()->render();
                ?>

            </div>
            <div class="col-md-10">
                <!-- Breadcrumbs -->
                <?= $this->pageBreadcrumbs()->render(); ?>

                <!-- Page content placeholder -->
                <?= $this->content; ?>

                <hr>

                <footer>
                    <p>
                        &copy; <?= date('Y') ?>
                        <a href="https://github.com/EDSManager">EDSManager</a>.
                    </p>
                </footer>
            </div>

        </div>

    <?= $this->inlineScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>
    </body>
</html>
