<?php
$this->headTitle('About');

$this->mainMenu()->setActiveItemId('about');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'About'=>$this->url('about'),
]);
?>

<div class="jumbotron">
    <h2><?= $this->escapeHtml($appName); ?></h2>
    <p>
    Версия: <?= $this->escapeHtml($appVersion); ?>.
    </p>

    <hr class="my-4">

    <p>
    <?= $this->escapeHtml($appDescription); ?>.
    </p>
</div>