<?php
$this->headTitle('Welcome');

$this->mainMenu()->setActiveItemId('library');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Library'=>$this->url('library'),
]);
?>

<div class="jumbotron">

    <h1 class="display-4">Бибилиотека</h1>

</div>

<div class="jumbotron">

<p>
    <a class="btn btn-info" href="
    <?= $this->url('library', ['action'=>'upload']); ?>">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Добавить файл
    </a>
</p>
</div>